https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  environment:
    STAGE: 'production'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  restart: always